name: Generate Snake

on:
  schedule: 
    - cron: "59 23 * * *" 
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: MarcoAn778
          outputs: dist/github-contribution-grid-snake.svg

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Criar branch output e commitar
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/output; then
            git checkout output
          else
            git checkout -b output
          fi
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Atualiza cobrinha" || echo "Sem alterações para commitar"
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
